services:
  influxdb:
    image: influxdb:2.7
    ports: ["8086:8086"]
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=gasper-org
      - DOCKER_INFLUXDB_INIT_BUCKET=gasper
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

  grafana:
    image: grafana/grafana:11.6.0
    ports: ["3000:3000"]
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    configs:
      - source: datasources
        target: /etc/grafana/provisioning/datasources/influxdb.yaml
      - source: dashboards_provider
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
      - source: blockspeed_dashboard
        target: /etc/grafana/provisioning/dashboards/blockspeed.json

configs:
  datasources:
    content: |
      apiVersion: 1
      datasources:
        - name: InfluxDB
          type: influxdb
          access: proxy
          url: http://influxdb:8086
          database: gasper
          isDefault: true
          jsonData:
            version: Flux
            organization: gasper-org
            defaultBucket: gasper
            tlsSkipVerify: true
          secureJsonData:
            token: my-token

  dashboards_provider:
    content: |
      apiVersion: 1
      providers:
        - name: 'Gasper'
          orgId: 1
          folder: ''
          folderUid: ''
          type: file
          disableDeletion: true
          editable: true
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /etc/grafana/provisioning/dashboards

  blockspeed_dashboard:
    file: ./dashboards/blockspeed.json
