{
 "title": "Blockspeed",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Mgas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mgas - Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_mgas\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> group(columns: [\"client_uid\", \"test_uid\"])"
    }
   ]
  },
  {
   "title": "Mgas - Max",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "ethereum_tps",
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_mgas\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"_time\", \"client_uid\", \"test_uid\"])\n  |> sum()\n  |> group(columns: [\"client_uid\", \"test_uid\"])\n  |> max()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TPS - Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_tps\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"_time\", \"client_uid\", \"test_uid\"])\n  |> sum()\n  |> group(columns: [\"client_uid\", \"test_uid\"])"
    }
   ]
  },
  {
   "title": "TPS - Max",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "ethereum_tps",
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_tps\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"_time\", \"client_uid\", \"test_uid\"])\n  |> sum()\n  |> group(columns: [\"client_uid\", \"test_uid\"])\n  |> max()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Tx Latency - Over Time (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_time_to_mine\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> group(columns: [\"client_uid\", \"test_uid\"])\n  |> aggregateWindow(\n      every: v.windowPeriod,\n      fn: mean,\n      createEmpty: false\n    )"
    }
   ]
  },
  { "title": "Gas Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Gas Used  - Over Time (Million)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_gas_used\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_uid\", \"client_uid\"])\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000.0 }))\n  |> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Gas Used - Max Per Block (Million)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ethereum_tps",
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_gas_used\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"_time\", \"client_uid\", \"test_uid\"])\n  |> sum()\n  |> group(columns: [\"client_uid\", \"test_uid\"])\n  |> max()\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000.0 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Txs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Mined Txs - Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_txs\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_uid\", \"client_uid\"])\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> map(fn: (r) => ({ r with _value: r._value }))\n  |> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Mined Txs - Max Per Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ethereum_tps",
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_txs\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"_time\", \"client_uid\", \"test_uid\"])\n  |> sum()\n  |> group(columns: [\"client_uid\", \"test_uid\"])\n  |> max()\n  |> map(fn: (r) => ({ r with _value: r._value }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "TxPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "TxPool Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_pool_status_pending\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_uid\", \"client_uid\"])\n  |> fill(value: 0.0)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "TxPool Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_pool_status_queued\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_uid\", \"client_uid\"])\n  |> aggregateWindow(\n      every: v.windowPeriod,\n      fn: sum,\n      createEmpty: false\n    )\n  |> fill(value: 0.0)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Num of Blocks per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_block_per_sec\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_uid\", \"client_uid\"])\n  |> aggregateWindow(\n      every: v.windowPeriod,\n      fn: sum,\n      createEmpty: false\n    )\n  |> fill(value: 0.0)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "EOA - Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"gasper\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"gasper_eoa\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"test_uid\", \"client_uid\", \"tx_type\"])\n  |> aggregateWindow(\n      every: v.windowPeriod,\n      fn: sum,\n      createEmpty: false\n    )\n  |> movingAverage(n: 100)\n  |> fill(value: 0.0)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  }
 ]
}